# Generated by Django 2.0 on 2019-01-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesLookApp', '0002_auto_20190119_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='look',
            name='clothes',
            field=models.ManyToManyField(to='clothesLookApp.Clothing'),
        ),
    ]
